import os
import pandas as pd
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt

class Process4Panels:
    """
    Process4Panels

    This class reconstructs and prepares all data products required for the
    multi-panel visualization (Panel 1–4 and Panel 6) in the Streamlit app.
    It loads the raw spectral data and the previously generated fitting 
    parameters, rebuilds fitted spectra, derives additional analysis outputs,
    and stores them in the standard output directory structure.

    The class produces the following files:

        • sum_fit.csv  
            Reconstructed spectra for each time step using the fitted 
            Lorentzian parameters (sum of all peaks including baseline).

        • substance_fits/substance_fit_<i>.csv  
            One CSV per time step containing reconstructed spectra grouped 
            by substance (Reactant, Metabolites, Water), including baseline.

        • individual_peak_fits/individual_peaks_fit_<i>.csv  
            One CSV per time step with every individual peak reconstructed 
            separately (without baseline), plus aggregated sum columns.

        • differences.csv  
            Residuals between the measured spectrum and the reconstructed 
            fitted spectrum for each time step. Used in Panel 3 (Noise).

        • kinetics.csv  
            Simple kinetic traces based on the summed amplitudes of peaks 
            per substance over time. Used for Panel 2 (Kinetics Plot).

    Workflow usage:
        1. After peak fitting is completed (PeakFitting class), the Streamlit
           app calls Process4Panels on the cleaned spectral data file.
        2. The class reconstructs levels of detail needed for interactive panels.
        3. The panels (Spectrum, Kinetics, Contour/Noise, Reference, Stacked)
           read the files generated by this class.

    Notes:
        – The class automatically normalizes decimal formats and removes invalid rows.
        – All reconstructed spectra use the Lorentzian parameters output by 
          the PeakFitting class.
        – The plotting itself is not handled here; this class only generates 
          the required numeric data for the visual layers.

    """

    def __init__(self, data_file_path):
        # prepare file paths
        self.data_file_path = data_file_path
        #self.file_name = os.path.basename(data_file_path)
        self.file_name = os.path.splitext(os.path.basename(data_file_path))[0]
        self.output_dir = Path('output', self.file_name + '_output')
        self.fitting_params_fp = Path(str(self.output_dir), 'fitting_params.csv')
        self.fitting_params_err_fp = Path(str(self.output_dir), 'fitting_params_error.csv')

        # read in necessary data with delimiter sniffing and normalize decimals
        self.data = pd.read_csv(self.data_file_path, sep=None, engine="python")

        # normalize European decimal commas and coerce to numeric
        for col in self.data.columns:
            if self.data[col].dtype == object:
                self.data[col] = self.data[col].astype(str).str.replace(",", ".", regex=False)
            self.data[col] = pd.to_numeric(self.data[col], errors="coerce")

        # clean NaN/inf rows and drop empty cols
        self.data.replace([np.inf, -np.inf], np.nan, inplace=True)
        self.data = self.data.dropna(axis=1, how="all")
        before_shape = self.data.shape
        self.data = self.data.dropna(axis=0, how="any")
        after_shape = self.data.shape
        print(f"[Process4Panels] Cleaned data: {before_shape} -> {after_shape} (rows x cols)")

        # rename first column to chemical_shift_ppm (independent of original name)
        shift_col = self.data.columns[0]
        self.data = self.data.rename(columns={shift_col: "chemical_shift_ppm"})

        self.fitting_params = pd.read_csv(self.fitting_params_fp)
        self.fitting_params_error = pd.read_csv(self.fitting_params_err_fp)

    def lorentzian(self, x, shift, gamma, A, y_shift):
        """
        Lorentzian line shape with baseline offset.

        Args:
            x (array-like): x-values (chemical shift).
            shift (float): Peak position (x0).
            gamma (float): Line width parameter.
            A (float): Amplitude.
            y_shift (float): Constant baseline offset.

        Returns:
            numpy.ndarray: Evaluated Lorentzian curve.
        """
        return A * gamma / ((x - shift)**2 + gamma**2) + y_shift
    
    def save_sum_spectra(self):
        """
        Reconstructs the sum of all Lorentzian peaks for each time step
        and saves the result to 'sum_fit.csv' in the output directory.
        """
        x = self.data.iloc[:,0]
        self.sum_df = pd.DataFrame({'x': x})
        for i, row in enumerate(self.fitting_params.iterrows()):
            n_peaks = int((len(row[1]) - 2) / 3)
            y_shift = row[1].iloc[1]
            positions = row[1][2:n_peaks+2]
            widths = row[1][2+n_peaks: 2*n_peaks+2]
            amplitudes = row[1][2*n_peaks+2:]
            y = np.zeros(len(x))
            for position,width, amplitude in zip(positions, widths, amplitudes):
                y += self.lorentzian(x, position, width, amplitude, y_shift)
            y = pd.DataFrame({'Time_Step_'+ str(i + 1): y})
            self.sum_df = pd.concat([self.sum_df, y] ,axis=1)
        self.sum_df.set_index('x')
        self.sum_df.to_csv(str(Path(str(self.output_dir), 'sum_fit.csv')),index=False)
    
    def save_substrate_individual(self):
        """
        Reconstructs Lorentzian fits per substance (grouped by name prefix)
        for each time frame and saves one CSV per frame in 'substance_fits'.
        """
        x = self.data.iloc[:,0]
        output_path = Path(str(self.output_dir), 'substance_fits')
        os.makedirs(str(output_path), exist_ok=True)

        for i, row in enumerate(self.fitting_params.iterrows()):
            n_peaks = int((len(row[1]) - 2) / 3)
            names = row[1].index[2:]  # This remains the same because `index` is used for column labels
            y_shift = row[1].iloc[1]
            positions = row[1].iloc[2:n_peaks + 2]
            widths = row[1].iloc[2 + n_peaks: 2 * n_peaks + 2]
            amplitudes = row[1].iloc[2 * n_peaks + 2:]
            time_frame_res = pd.DataFrame({'x': x})
            
            # group positons according to substances
            substances = set([name.split('_')[0] for name in names])
            for substance in substances:
                indices = []
                # get positions 
                indices = [idx for idx, name in enumerate(names[:n_peaks]) if substance in name]

                rel_pos = positions.iloc[indices]
                rel_width = widths.iloc[indices]
                rel_ampl = amplitudes.iloc[indices]

                y = np.zeros(len(x))
                for position,width, amplitude in zip(rel_pos, rel_width, rel_ampl):
                    y += self.lorentzian(x, position,width, amplitude, y_shift)
                y = pd.DataFrame({substance : y})
                time_frame_res = pd.concat([time_frame_res, y], axis = 1)
            
            time_frame_res.to_csv(str(Path(str(output_path), f'substance_fit_{i + 1}.csv')), index=False)

    def save_individual_peaks(self):
        """
        Saves each individual peak (without baseline) as a separate column,
        and adds aggregate columns for:
            - sum of all peaks without baseline,
            - baseline value,
            - sum of all peaks including baseline.

        One CSV file per time frame is written to 'individual_peak_fits'.
        """
        x = self.data.iloc[:,0]
        output_path = Path(str(self.output_dir), 'individual_peak_fits')
        os.makedirs(str(output_path), exist_ok=True)

        # Lorentzian WITHOUT y_shift (Baseline)
        def lorentzian_core(x, shift, gamma, A):
            return A * gamma / ((x - shift)**2 + gamma**2)

        for i, row in enumerate(self.fitting_params.iterrows()):
            n_peaks = int((len(row[1]) - 2) / 3)
            names = row[1].index[2:]   # Peak-Namen
            y_shift = row[1].iloc[1]
            positions = row[1].iloc[2:n_peaks + 2]
            widths    = row[1].iloc[2 + n_peaks: 2 * n_peaks + 2]
            amplitudes= row[1].iloc[2 * n_peaks + 2:]

            time_frame_res = pd.DataFrame({'x': x})

            # Peaks WITHOUT Baseline as individual columns
            peak_cols = []
            for idx in range(n_peaks):
                peak_name = names[idx]
                pos  = positions.iloc[idx]
                wid  = widths.iloc[idx]
                ampl = amplitudes.iloc[idx]

                y_peak = lorentzian_core(x, pos, wid, ampl)  # no Baseline!
                time_frame_res[peak_name] = y_peak
                peak_cols.append(peak_name)

            # Sum-Columns
            time_frame_res["Sum_Peaks_no_baseline"] = time_frame_res[peak_cols].sum(axis=1)
            time_frame_res["Baseline"] = y_shift
            time_frame_res["Sum_Peaks_with_baseline"] = time_frame_res["Sum_Peaks_no_baseline"] + y_shift

            # save
            output_file = Path(str(output_path), f'individual_peaks_fit_{i + 1}.csv')
            time_frame_res.to_csv(str(output_file), index=False)

        print(f"Individual peak fits saved to: {output_path}")

    def save_difference(self):
        """
        Computes the difference between measured spectra and reconstructed
        sum spectra and saves them to 'differences.csv'.

        The method is robust to:
        - missing `sum_df` (requires `save_sum_spectra()` to be called first),
        - differing lengths between data and sum_df columns,
        - cases without any usable spectrum columns.
        """
        # ensure sum_df exists
        if not hasattr(self, "sum_df"):
            print("[Process4Panels] save_difference: sum_df nicht vorhanden – hast du save_sum_spectra() aufgerufen?")
            return

        # x-axis
        x = self.data.iloc[:, 0].reset_index(drop=True)
        differences = pd.DataFrame({'x': x})

        # number of columns that can be compared
        # (at least 1 column = x, remaining columns are spectra)
        n_cols_data = self.data.shape[1]
        n_cols_sum  = self.sum_df.shape[1]
        n_cols = min(n_cols_data, n_cols_sum)

        # if there are no spectrum columns, only save x and return
        if n_cols <= 1:
            out_path = Path(self.output_dir) / "differences.csv"
            differences.to_csv(out_path, index=False)
            print(f"[Process4Panels] save_difference: keine Spektrums-Spalten, schreibe nur x nach {out_path}")
            return

        diff_columns = []
        min_len_global = len(x)

        for i in range(1, n_cols):  # start from column 1 (column 0 = x)
            data_col = self.data.iloc[:, i].reset_index(drop=True)
            fit_col  = self.sum_df.iloc[:, i].reset_index(drop=True)

            min_len = min(len(data_col), len(fit_col))
            if min_len == 0:
                continue  

            min_len_global = min(min_len_global, min_len)
            diff = data_col.iloc[:min_len] - fit_col.iloc[:min_len]
            diff_columns.append(diff.reset_index(drop=True))

        # if no difference columns could be computed, just save x and exit
        if not diff_columns:
            out_path = Path(self.output_dir) / "differences.csv"
            differences.to_csv(out_path, index=False)
            print(f"[Process4Panels] save_difference: keine Differenzspalten berechnet, schreibe nur x nach {out_path}")
            return

        # now concatenate safely
        diff_df = pd.concat(diff_columns, axis=1)
        diff_df.columns = [f"Time_Step_{i}" for i in range(1, diff_df.shape[1] + 1)]

        # shorten x to common length
        differences = pd.concat([differences.iloc[:min_len_global], diff_df.iloc[:min_len_global, :]], axis=1)

        # save
        out_path = Path(self.output_dir) / "differences.csv"
        differences.to_csv(out_path, index=False)
        print(f"[Process4Panels] differences.csv saved to {out_path}")
        
    def save_kinetics(self):
        """
        Computes simple kinetic traces per substance by summing peak amplitudes
        per time step and saves them to 'kinetics.csv'.

        Notes:
            - The integral of a Lorentzian is proportional to the amplitude,
              so amplitudes are used as a proxy here.
            - Peaks are grouped by their substance name prefix (before '_').
        """
        n_peaks = self.fitting_params.shape[1] // 3
        names = self.fitting_params.columns[2:] 

        substances = list(set([name.split('_')[0] for name in names]))

        kinetics = np.zeros((self.fitting_params.shape[0],len(substances)))

        # the integral is approximated by the amplitude
        for i, row in enumerate(self.fitting_params.iterrows()):
            amplitudes = row[1].iloc[2 * n_peaks + 2:]
            # group positons according to substances, unnecessary loop. complete waste of computational resources
            for k, substance in enumerate(substances):
                indices = []
                # get positions 
                indices = [idx for idx, name in enumerate(names[:n_peaks]) if substance in name]
                # row i and columns k
                kinetics[i,k] = sum(amplitudes.iloc[indices].values)
        kinetics = pd.DataFrame(kinetics, columns = substances)
        kinetics['Time_Step'] = np.arange(1, kinetics.shape[0]+1)
        kinetics.set_index('Time_Step', inplace=True)
        kinetics.to_csv(Path(self.output_dir, 'kinetics.csv'))